/*
 * @Date: 2022-01-24 16:50:25
 * @LastEditors: zhangheng
 * @LastEditTime: 2022-04-17 14:01:23
 */
export const CHANGE_ARTICLE = 'CHANGE_ARTICLE';
export const CHANGE_ARTICLE_COUNT = 'CHANGE_ARTICLE_COUNT';
export const CHANGE_QUERY = 'CHANGE_QUERY';
export const CHANGE_ARTICLELOADING = 'CHANGE_ARTICLELOADING';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
