/*
 * @Date: 2022-01-24 16:50:25
 * @LastEditors: zhangheng
 * @LastEditTime: 2023-02-21 20:52:13
 */
export const CHANGE_ARTICLEINFO = 'CHANGE_ARTICLEINFO';
export const CHANGE_ARTICLE_DETAIL_LOADING = 'CHANGE_ARTICLE_DETAIL_LOADING';
export const CHANGE_COMMENT_LIST = 'CHANGE_COMMENT_LIST';
export const CHANGE_COMMENT_LIST_TOTAL_COUNT = 'CHANGE_COMMENT_LIST_TOTAL_COUNT';
